services:
  # LE BACKEND (API)
  - type: web
    name: forfeo-supply-api
    env: node
    plan: free
    root: backend
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false

  # LE FRONTEND (React)
  - type: web
    name: forfeo-supply-web
    env: static
    plan: free
    root: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: forfeo-supply-api
          property: url
